export const routes = {
    home: '/',
    contact: '/contact',
    reservation: '/reservation',
    company: '/company',
    about: '/about',
    menu: '/menu',
    mainMenu: "/mainMenu",
    privacyPolicy: "/privacy-policy",
    news: "/news",
    about_message: "/about/message",
    about_feature: "/about/feature",
    about_important: "/about/important",
    about_academy: "/about/academy",
    about_product: "/about/product",
    about_access: "/about/access",
    product: "/product",
    authentication_email: "/authentication_email",
}